baseurl = "https://www.mattandreko.com/"
languageCode = "en-US"
title = "Matt Andreko"
disqusShortname = "mattandreko"

theme = "hugo-pixel"
Paginate = 6

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "mattandreko_photo.jpg"
  author = "Matt Andreko"
  author_description = "Security Consultant"
  disqusShortname = "mattandreko"
  googleAnalytics = "UA-25280110-1"

  generateTaxonomyList = true
  sortTaxonomyAlphabetical = true

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[indexes]
  category = "categories"

[params.social]
  Facebook      = "mattandreko"
  Twitter       = "mandreko"
  GooglePlus    = "mandreko"
  LinkedIn      = "mattandreko"
  StackOverflow = "mattandreko"
  Github        = "mandreko"
  Instagram     = "mandreko"
  Email         = "mandreko@gmail.com"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"

[[menu.sidebar]]
  Name = "Google"
  URL = "https://www.google.com"
  weight = 0
[[menu.sidebar]]
  Name = "Hugo"
  URL = "/categories/hugo/"
  weight = 1
