baseurl = "http://test.andreko.net/"
languageCode = "en-US"
title = "Matt Andreko"

theme = "hugo-pixel"

# to make it work with github pages
publishDir = "docs"

[permalinks]
  blog = "/:year/:month/:day/:slug/"

[params]
  paginate = 8
  topCategoriesCount = 8

  avatar = "mattandreko_photo.jpg"
  author = "Matt Andreko"
  author_description = "Security Consultant"
  googleAnalytics = "UA-25280110-1"
  
  disqusShortname = "mattandreko"
  # Disable comments for a specific post by adding "comments: false" in its frontmatter

  generateTaxonomyList = true
  sortTaxonomyAlphabetical = false

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[indexes]
  category = "categories"

[params.social]
  Facebook      = "mattandreko"
  Twitter       = "mandreko"
  GooglePlus    = "mandreko"
  LinkedIn      = "mattandreko"
  StackOverflow = "mattandreko"
  Github        = "mandreko"
  Instagram     = "mandreko"
  Email         = "mandreko@gmail.com"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"

[[menu.sidebar]]
  Name = "Google"
  URL = "https://www.google.com"
  weight = 0
[[menu.sidebar]]
  Name = "Hugo"
  URL = "/categories/hugo/"
  weight = 1
