name = "mattandreko"
license = "MIT"
licenselink = "https://github.com/mandreko/hugo-pixel/blob/master/LICENSE.md"
description = "Personal blog built with Bootstrap, powered by Hugo"
homepage = "https://github.com/mandreko/hugo-pixel"
tags = ["blog", "minimal", "responsive"]
features = ["responsive", "syntax highlighting"]
min_version = 0.17

[author]
  name = "Matt Andreko"
  homepage = "https://github.com/mandreko"

# If porting an existing theme
[original]
  name = "Pixel"
  homepage = "https://github.com/mandreko/hugo-pixel"
  repo = "https://github.com/mandreko/hugo-pixel"
