# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Pixel"
license = "MIT"
licenselink = "https://github.com/mandreko/hugo-pixel/blob/master/LICENSE.md"
description = ""
homepage = "http://www.mattandreko.com/"
tags = []
features = []
min_version = 0.19

[author]
  name = "Matt Andreko"
  homepage = "http://www.mattandreko.com/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
