# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Pixel"
license = "MIT"
description = ""
homepage = "http://www.mattandreko.com/"
tags = []
features = []
min_version = 0.19

[author]
  name = "Matt Andreko"
  homepage = "http://www.mattandreko.com/"
